cuda.{mk.in,ac},configure,Makefile.in: more CUDA `configure` options, docs
  * Moved `configure`-time CUDA configuration values to `cuda.mk.in`.
  * Added --with-cuda-sdk=PATH option => CUDA_SDK_DIR in cuda.mk
  * Added additional documentation to cuda.ac
  * Added HAVE_CUDA and HAVE_CUDA_SDK vars to cuda.mk

Change-Id: I893b4fbcfb8e6808c3bf3f429765dfa718d72088

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -638,6 +638,7 @@ ac_includes_default="\
 #endif"
 
 <<<<<<< Upstream, based on master
+<<<<<<< Upstream, based on master
 ac_subst_vars='LTLIBOBJS
 LIBOBJS
 OBJECTS_COOLING
@@ -703,6 +704,9 @@ SHELL'
 =======
 ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS CHARMC CHARM_PATH AR CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT CC CFLAGS ac_ct_CC CPP EGREP FLAG_BIGKEYS FLAG_COOLING OBJECTS_COOLING LIBOBJS CUDA_DIR NVCC_PATH ENABLE_CUDA LTLIBOBJS'
 >>>>>>> bc9002e configure{,.ac}: Added CUDA toolkit detection
+=======
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS CHARMC CHARM_PATH AR CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT CC CFLAGS ac_ct_CC CPP EGREP FLAG_BIGKEYS FLAG_COOLING OBJECTS_COOLING LIBOBJS CUDA_DIR NVCC_PATH CUDA_SDK_DIR ENABLE_CUDA HAVE_CUDA HAVE_CUDA_SDK LTLIBOBJS'
+>>>>>>> 1e7f5f9 cuda.{mk.in,ac},configure,Makefile.in: more CUDA `configure` options, docs
 ac_subst_files=''
 ac_user_opts='
 enable_option_checking
@@ -1321,7 +1325,14 @@ ac_env_CUDA_DIR_set=${CUDA_DIR+set}
 ac_env_CUDA_DIR_value=$CUDA_DIR
 ac_cv_env_CUDA_DIR_set=${CUDA_DIR+set}
 ac_cv_env_CUDA_DIR_value=$CUDA_DIR
+<<<<<<< Upstream, based on master
 >>>>>>> bc9002e configure{,.ac}: Added CUDA toolkit detection
+=======
+ac_env_CUDA_SDK_DIR_set=${CUDA_SDK_DIR+set}
+ac_env_CUDA_SDK_DIR_value=$CUDA_SDK_DIR
+ac_cv_env_CUDA_SDK_DIR_set=${CUDA_SDK_DIR+set}
+ac_cv_env_CUDA_SDK_DIR_value=$CUDA_SDK_DIR
+>>>>>>> 1e7f5f9 cuda.{mk.in,ac},configure,Makefile.in: more CUDA `configure` options, docs
 
 #
 # Report the --help message.
@@ -1411,6 +1422,7 @@ Optional Packages:
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
   --with-cuda[=PATH]
                           use CUDA (installed in PATH) [no]
+  --with-cuda-sdk=PATH    specify the CUDA SDK install directory
 
 Some influential environment variables:
   CHARMC      "Charm compiler"
@@ -1425,6 +1437,8 @@ Some influential environment variables:
   CFLAGS      C compiler flags
   CPP         C preprocessor
   CUDA_DIR    CUDA toolkit install directory
+  CUDA_SDK_DIR
+              CUDA SDK install directory
 
 Use these variables to override the choices made by `configure' or to help
 it to find libraries and programs with nonstandard names/locations.
@@ -6675,15 +6689,37 @@ ac_config_files="$ac_config_files Makefile ../utility/structures/Makefile"
 #					installed CUDA toolkit package on Debian
 #                                       and Debian-based systems
 #
+# On successful search, these variables are set in the generated cuda.mk:
+#
+#   * HAVE_CUDA and ENABLE_CUDA: set to "yes"
+#   * CUDA_DIR: set to the found CUDA toolkit directory
+#   * NVCC: set to the location of the `nvcc` binary in the CUDA toolkit
+#     directory
+#
+# We also define a `--with-cuda-sdk=PATH` option, which allows the user to
+# specify the install location of nVidia's CUDA SDK.  Unlike the `--with-cuda`
+# option, `--with-cuda-sdk` does no automatic search and requires an argument.
+# If the argument exists and is a directory, the following variables are set in
+# the generated cuda.mk.
+#
+#   * HAVE_CUDA_SDK: set to "yes"
+#   * CUDA_SDK_DIR: set to the path given as an argument to `--with-cuda-sdk`.
+#
+#
 # There are some arguments to AC_MSG_* with ugly formatting here; the formatting
 # is intentional (it produces nice, readable output in the generated `configure`
-# script).
+# script, and keeps lines under 80 characters in length).
 #
-# To enable automatic "use" of CUDA (i.e., setting ENABLE_CUDA to "yes" if CUDA
-# is found), change the assigned value of `ENABLE_CUDA` in the line directly
-# below this comment to "auto".  (You should also change the default-argument
-# value in the docstring passed to `AS_HELP_STRING` to match.)
+# To enable automatic "use" of CUDA (i.e., setting ENABLE_CUDA to "yes" if the
+# CUDA toolkit is found), change the assigned value of `ENABLE_CUDA` in the
+# line directly below this comment to "auto".  (You should also change the
+# default-argument value in the docstring passed to `AS_HELP_STRING` for
+# `--with-cuda` to match.)
 ENABLE_CUDA="no"
+
+HAVE_CUDA="no"
+HAVE_CUDA_SDK="no"
+
 
 
 
@@ -6695,23 +6731,31 @@ else
   CUDA_DIR=""
 fi;
 
+# If CUDA_DIR is set, it's because the user gave the --with-cuda option in at
+# least _one_ of the valid forms.
+if test -n "$CUDA_DIR"; then
+    ENABLE_CUDA="yes"
+fi
+
 # Interpret "--with-cuda" (i.e. no argument) as "enable CUDA support, please."
 # We also support using the argument "auto" for this purpose.
 if test "$CUDA_DIR" = "yes" || test "$CUDA_DIR" = "auto"; then
-    ENABLE_CUDA="yes"
     CUDA_DIR=""
 fi
 
 if test "$ENABLE_CUDA" != "no"; then
+    echo "$as_me:$LINENO: checking for CUDA toolkit directory" >&5
+echo $ECHO_N "checking for CUDA toolkit directory... $ECHO_C" >&6
     if test -z "$CUDA_DIR"; then
         CUDA_DIR_AUTOMATIC=yes
-        echo "$as_me:$LINENO: checking for CUDA toolkit directory" >&5
-echo $ECHO_N "checking for CUDA toolkit directory... $ECHO_C" >&6
         CUDA_CANDIDATE_DIRS="/usr/local/cuda /usr/lib/nvidia-cuda-toolkit"
 
         for dir in $CUDA_CANDIDATE_DIRS; do
             if test -d "$dir"; then
                 CUDA_DIR="$dir"
+                HAVE_CUDA="yes"
+                echo "$as_me:$LINENO: result: $CUDA_DIR" >&5
+echo "${ECHO_T}$CUDA_DIR" >&6
                 break
             fi
         done
@@ -6732,11 +6776,21 @@ CUDA support explicitly enabled but the toolkit was not found by automatic path
             else
                 echo "$as_me:$LINENO: result: not found.  CUDA support will be disabled." >&5
 echo "${ECHO_T}not found.  CUDA support will be disabled." >&6
-                ENABLE_CUDA=no
+                ENABLE_CUDA="no"
+                HAVE_CUDA="no"
             fi
-        else
+        fi
+    else                    # User gave explicit toolkit location.
+        if test -d "$CUDA_DIR"; then
             echo "$as_me:$LINENO: result: $CUDA_DIR" >&5
 echo "${ECHO_T}$CUDA_DIR" >&6
+            HAVE_CUDA="yes"
+        else
+            echo "$as_me:$LINENO: result: not found" >&5
+echo "${ECHO_T}not found" >&6
+            { { echo "$as_me:$LINENO: error: specified CUDA toolkit directory not found." >&5
+echo "$as_me: error: specified CUDA toolkit directory not found." >&2;}
+   { (exit 1); exit 1; }; }
         fi
     fi
 fi
@@ -6794,8 +6848,10 @@ echo "$as_me: error: \
     CUDA toolkit location with \`--with-cuda=PATH\`." >&2;}
    { (exit 1); exit 1; }; }
             else
-                { { echo "$as_me:$LINENO: error: \`bin/nvcc\` not found in specified CUDA install prefix." >&5
-echo "$as_me: error: \`bin/nvcc\` not found in specified CUDA install prefix." >&2;}
+                { { echo "$as_me:$LINENO: error: \
+\`bin/nvcc\` not found in specified CUDA toolkit install prefix." >&5
+echo "$as_me: error: \
+\`bin/nvcc\` not found in specified CUDA toolkit install prefix." >&2;}
    { (exit 1); exit 1; }; }
             fi
         else                    # ENABLE_CUDA is "auto"
@@ -6808,20 +6864,55 @@ echo "$as_me: \
     support will be disabled.  If this is not what you want, try specifying a
     valid CUDA toolkit install prefix using \`--with-cuda=PATH\`." >&6;}
             ENABLE_CUDA="no"
+            HAVE_CUDA="no"
         fi
     fi
 fi
 
-# Set up `ENABLE_CUDA` for use by Make.
-if test "$ENABLE_CUDA" = "no"; then
-    ENABLE_CUDA=""
+
+# Check for the CUDA SDK.
+
+
+# Check whether --with-cuda-sdk or --without-cuda-sdk was given.
+if test "${with_cuda_sdk+set}" = set; then
+  withval="$with_cuda_sdk"
+  CUDA_SDK_DIR=$withval
 else
-    ENABLE_CUDA="yes"
+  CUDA_SDK_DIR=""
+fi;
+
+if test -n "$CUDA_SDK_DIR"; then
+    echo "$as_me:$LINENO: checking for CUDA SDK directory" >&5
+echo $ECHO_N "checking for CUDA SDK directory... $ECHO_C" >&6
+    if test -d "$CUDA_SDK_DIR"; then
+        echo "$as_me:$LINENO: result: $CUDA_SDK_DIR" >&5
+echo "${ECHO_T}$CUDA_SDK_DIR" >&6
+        HAVE_CUDA_SDK=yes
+    else
+        echo "$as_me:$LINENO: result: not found" >&5
+echo "${ECHO_T}not found" >&6
+        { { echo "$as_me:$LINENO: error: specified CUDA SDK directory not found." >&5
+echo "$as_me: error: specified CUDA SDK directory not found." >&2;}
+   { (exit 1); exit 1; }; }
+    fi
 fi
 
+# Set up boolean AC_SUBST variables for use in Make.
+for var in HAVE_CUDA HAVE_CUDA_SDK ENABLE_CUDA; do
+    eval value='$'"$var"
+    if test "$value" = "no"; then
+        eval "$var=''"
+    fi
+done
 
 
 
+
+
+
+
+
+          ac_config_files="$ac_config_files cuda.mk"
 
 
 ##################### END CUDA #####################
@@ -7435,6 +7526,7 @@ $as_echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
 =======
   case "$ac_config_target" in
   # Handling of arguments.
+  "cuda.mk" ) CONFIG_FILES="$CONFIG_FILES cuda.mk" ;;
   "Makefile" ) CONFIG_FILES="$CONFIG_FILES Makefile" ;;
   "$srcdir/../utility/structures/Makefile" ) CONFIG_FILES="$CONFIG_FILES $srcdir/../utility/structures/Makefile" ;;
   "config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS config.h" ;;
@@ -7558,7 +7650,10 @@ s,@OBJECTS_COOLING@,$OBJECTS_COOLING,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
 s,@CUDA_DIR@,$CUDA_DIR,;t t
 s,@NVCC_PATH@,$NVCC_PATH,;t t
+s,@CUDA_SDK_DIR@,$CUDA_SDK_DIR,;t t
 s,@ENABLE_CUDA@,$ENABLE_CUDA,;t t
+s,@HAVE_CUDA@,$HAVE_CUDA,;t t
+s,@HAVE_CUDA_SDK@,$HAVE_CUDA_SDK,;t t
 s,@LTLIBOBJS@,$LTLIBOBJS,;t t
 CEOF
 
