configure.ac:  moved CUDA detection script to a separate file `cuda.ac`
Also added some cleanups related CUDA-related variable names

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -866,9 +866,7 @@ Optional Features:
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
-  --with-cuda[=PATH]
-                          Use CUDA (installed in PATH)
-                          [unspecified=auto]
+  --with-cuda[=PATH] Use CUDA (installed in PATH) [auto]
 
 Some influential environment variables:
   CHARMC      "Charm compiler"
@@ -5375,6 +5373,172 @@ _ACEOF
 
 fi
 done
+
+
+####################### CUDA #######################
+# ----------------------------------------------------------------
+# CUDA support
+#
+# Here we define and process a `--with-cuda[=PREFIX]` option.
+#
+# If the option is not given, or is given without an argument or with an
+# argument of "yes", we search for CUDA in the following locations:
+#
+#   /usr/local/cuda			standard CUDA install directory
+#
+#   /usr/lib/nvidia-cuda-toolkit 	install directory for the system-
+#					installed CUDA toolkit package on Debian
+#                                       and Debian-based systems
+#
+# There are some arguments to AC_MSG_* with ugly formatting here; the formatting
+# is intentional (it produces nice, readable output in the generated `configure`
+# script).
+#
+# To disable automatic use of CUDA, change the assigned value of `ENABLE_CUDA`
+# in the line directly below this comment to "no".  (You should also change the
+# default-argument value in the docstring passed to `AS_HELP_STRING` to match.)
+ENABLE_CUDA="auto"
+
+
+
+
+# Check whether --with-cuda or --without-cuda was given.
+if test "${with_cuda+set}" = set; then
+  withval="$with_cuda"
+  CUDA_DIR=$withval
+else
+  CUDA_DIR=""
+fi;
+
+# Interpret "--with-cuda" (i.e. no argument) as "enable CUDA support, please."
+# We also support using the argument "auto" for this purpose.
+if test "$CUDA_DIR" = "yes" || test "$CUDA_DIR" = "auto"; then
+    ENABLE_CUDA="yes"
+    CUDA_DIR=""
+fi
+
+if test "$ENABLE_CUDA" != "no"; then
+    if test -z "$CUDA_DIR"; then
+        CUDA_DIR_AUTOMATIC=yes
+        echo "$as_me:$LINENO: checking for CUDA toolkit directory" >&5
+echo $ECHO_N "checking for CUDA toolkit directory... $ECHO_C" >&6
+        CUDA_CANDIDATE_DIRS="/usr/local/cuda /usr/lib/nvidia-cuda-toolkit"
+
+        for dir in $CUDA_CANDIDATE_DIRS; do
+            if test -d "$dir"; then
+                CUDA_DIR="$dir"
+                break
+            fi
+        done
+        if test -z "$CUDA_DIR"; then
+            if test "$ENABLE_CUDA" = "yes"; then
+                # User explicitly requested CUDA support; being unable to find a
+                # toolkit directory is an error.
+                echo "$as_me:$LINENO: result: not found" >&5
+echo "${ECHO_T}not found" >&6
+                { { echo "$as_me:$LINENO: error: \
+CUDA support explicitly enabled but the toolkit was not found by automatic path
+    search.  Specify CUDA toolkit location with \`--with-cuda=PATH\`." >&5
+echo "$as_me: error: \
+CUDA support explicitly enabled but the toolkit was not found by automatic path
+    search.  Specify CUDA toolkit location with \`--with-cuda=PATH\`." >&2;}
+   { (exit 1); exit 1; }; }
+
+            else
+                echo "$as_me:$LINENO: result: not found.  CUDA support will be disabled." >&5
+echo "${ECHO_T}not found.  CUDA support will be disabled." >&6
+                ENABLE_CUDA=no
+            fi
+        else
+            echo "$as_me:$LINENO: result: $CUDA_DIR" >&5
+echo "${ECHO_T}$CUDA_DIR" >&6
+        fi
+    fi
+fi
+
+if test "$ENABLE_CUDA" != "no"; then
+    # Extract the first word of "nvcc", so it can be a program name with args.
+set dummy nvcc; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_NVCC_PATH+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $NVCC_PATH in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_NVCC_PATH="$NVCC_PATH" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $CUDA_DIR/bin
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_NVCC_PATH="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  ;;
+esac
+fi
+NVCC_PATH=$ac_cv_path_NVCC_PATH
+
+if test -n "$NVCC_PATH"; then
+  echo "$as_me:$LINENO: result: $NVCC_PATH" >&5
+echo "${ECHO_T}$NVCC_PATH" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+    if test -z "$NVCC_PATH" ; then
+        if test "$ENABLE_CUDA" = "yes"; then
+            if test "$CUDA_DIR_AUTOMATIC" = "yes"; then
+                { { echo "$as_me:$LINENO: error: \
+\`bin/nvcc\` not found in automatically-selected CUDA toolkit directory.  Specify
+    CUDA toolkit location with \`--with-cuda=PATH\`." >&5
+echo "$as_me: error: \
+\`bin/nvcc\` not found in automatically-selected CUDA toolkit directory.  Specify
+    CUDA toolkit location with \`--with-cuda=PATH\`." >&2;}
+   { (exit 1); exit 1; }; }
+
+            else
+                { { echo "$as_me:$LINENO: error: \`bin/nvcc\` not found in specified CUDA install prefix." >&5
+echo "$as_me: error: \`bin/nvcc\` not found in specified CUDA install prefix." >&2;}
+   { (exit 1); exit 1; }; }
+            fi
+        else                    # ENABLE_CUDA is "auto"
+            { echo "$as_me:$LINENO: \
+\`bin/nvcc\` not found in automatically-selected CUDA toolkit directory; CUDA
+    support will be disabled.  If this is not what you want, try specifying a
+    valid CUDA toolkit install prefix using \`--with-cuda=PATH\`." >&5
+echo "$as_me: \
+\`bin/nvcc\` not found in automatically-selected CUDA toolkit directory; CUDA
+    support will be disabled.  If this is not what you want, try specifying a
+    valid CUDA toolkit install prefix using \`--with-cuda=PATH\`." >&6;}
+            ENABLE_CUDA="no"
+        fi
+    fi
+fi
+
+# Set up `ENABLE_CUDA` for use by Make.
+if test "$ENABLE_CUDA" = "no"; then
+    ENABLE_CUDA=""
+else
+    ENABLE_CUDA="yes"
+fi
+
+
+
+
+
+           # include CUDA detection script
+##################### END CUDA #####################
 
 
                     ac_config_files="$ac_config_files Makefile $srcdir/../utility/structures/Makefile"
