made a few modifications to compile on IBM SP4 with mpi-sp-mpcc64

diff --git a/changa/configure b/changa/configure
--- a/changa/configure
+++ b/changa/configure
@@ -311,7 +311,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS CHARMC CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT CC CFLAGS ac_ct_CC CPP EGREP LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS CHARMC AR CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT CC CFLAGS ac_ct_CC CPP EGREP LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -1378,8 +1378,31 @@ CXX=${CMK_SEQ_CXX}
 CC=${CMK_SEQ_CC}
 LD=${CMK_SEQ_LD}
 LDXX=${CMK_SEQ_LDXX}
+AR=${CMK_AR}
+
 CPPFLAGS="$CPPFLAGS -I.."
 LDFLAGS="$LDFLAGS -L../libs"
+echo "$as_me:$LINENO: checking for ../libs" >&5
+echo $ECHO_N "checking for ../libs... $ECHO_C" >&6
+if test "${ac_cv_file____libs+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  test "$cross_compiling" = yes &&
+  { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
+echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
+   { (exit 1); exit 1; }; }
+if test -r "../libs"; then
+  ac_cv_file____libs=yes
+else
+  ac_cv_file____libs=no
+fi
+fi
+echo "$as_me:$LINENO: result: $ac_cv_file____libs" >&5
+echo "${ECHO_T}$ac_cv_file____libs" >&6
+if test $ac_cv_file____libs = yes; then
+  LDFLAGS="$LDFLAGS -L../libs"
+fi
+
 
 ac_ext=cc
 ac_cpp='$CXXCPP $CPPFLAGS'
@@ -5570,6 +5593,7 @@ s,@ECHO_N@,$ECHO_N,;t t
 s,@ECHO_T@,$ECHO_T,;t t
 s,@LIBS@,$LIBS,;t t
 s,@CHARMC@,$CHARMC,;t t
+s,@AR@,$AR,;t t
 s,@CXX@,$CXX,;t t
 s,@CXXFLAGS@,$CXXFLAGS,;t t
 s,@LDFLAGS@,$LDFLAGS,;t t
