Fix configure problems; particularly with structures.

diff --git a/changa/configure b/changa/configure
--- a/changa/configure
+++ b/changa/configure
@@ -1315,7 +1315,7 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 
 
-          ac_config_headers="$ac_config_headers config.h"
+                    ac_config_headers="$ac_config_headers config.h ../structures/config.h"
 
 
 
@@ -3155,7 +3155,9 @@ done
 
 
 
-for ac_header in limits.h malloc.h stddef.h stdint.h stdlib.h string.h sys/param.h unistd.h values.h
+
+
+for ac_header in sys/bittypes.h endian.h limits.h malloc.h stddef.h stdint.h stdlib.h string.h sys/param.h unistd.h values.h
 do
 as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
 if eval "test \"\${$as_ac_Header+set}\" = set"; then
@@ -3765,12 +3767,75 @@ fi
 echo "$as_me:$LINENO: result: $ac_cv_type_u_int64_t" >&5
 echo "${ECHO_T}$ac_cv_type_u_int64_t" >&6
 if test $ac_cv_type_u_int64_t = yes; then
-  :
-else
 
 cat >>confdefs.h <<_ACEOF
-#define u_int64_t uint64_t
+#define HAVE_U_INT64_T 1
 _ACEOF
+
+
+fi
+echo "$as_me:$LINENO: checking for u_quad_t" >&5
+echo $ECHO_N "checking for u_quad_t... $ECHO_C" >&6
+if test "${ac_cv_type_u_quad_t+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+int
+main ()
+{
+if ((u_quad_t *) 0)
+  return 0;
+if (sizeof (u_quad_t))
+  return 0;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_type_u_quad_t=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_type_u_quad_t=no
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: $ac_cv_type_u_quad_t" >&5
+echo "${ECHO_T}$ac_cv_type_u_quad_t" >&6
+if test $ac_cv_type_u_quad_t = yes; then
+
+cat >>confdefs.h <<_ACEOF
+#define HAVE_U_QUAD_T 1
+_ACEOF
+
 
 fi
 
@@ -4242,7 +4307,9 @@ fi
 
 
 
-for ac_func in memset pow sqrt strchr
+
+
+for ac_func in floor memset pow sqrt strchr xdr_hyper
 do
 as_ac_var=`echo "ac_cv_func_$ac_func" | $as_tr_sh`
 echo "$as_me:$LINENO: checking for $ac_func" >&5
@@ -4873,6 +4940,7 @@ do
   "Makefile" ) CONFIG_FILES="$CONFIG_FILES Makefile" ;;
   "../structures/Makefile" ) CONFIG_FILES="$CONFIG_FILES ../structures/Makefile" ;;
   "config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS config.h" ;;
+  "../structures/config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS ../structures/config.h" ;;
   *) { { echo "$as_me:$LINENO: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
