Better handling of "xdr" on Bluegene.

diff --git a/changa/configure b/changa/configure
--- a/changa/configure
+++ b/changa/configure
@@ -3487,18 +3487,18 @@ fi
 if test "${MISSING_NETINET}" = "yes" ; then
    CPPFLAGS="$CPPFLAGS -I/usr/include"
 fi
-if test "${ac_cv_header_rpc_rpc_h+set}" = set; then
-  echo "$as_me:$LINENO: checking for rpc/rpc.h" >&5
-echo $ECHO_N "checking for rpc/rpc.h... $ECHO_C" >&6
-if test "${ac_cv_header_rpc_rpc_h+set}" = set; then
+if test "${ac_cv_header_rpc_xdr_h+set}" = set; then
+  echo "$as_me:$LINENO: checking for rpc/xdr.h" >&5
+echo $ECHO_N "checking for rpc/xdr.h... $ECHO_C" >&6
+if test "${ac_cv_header_rpc_xdr_h+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 fi
-echo "$as_me:$LINENO: result: $ac_cv_header_rpc_rpc_h" >&5
-echo "${ECHO_T}$ac_cv_header_rpc_rpc_h" >&6
+echo "$as_me:$LINENO: result: $ac_cv_header_rpc_xdr_h" >&5
+echo "${ECHO_T}$ac_cv_header_rpc_xdr_h" >&6
 else
   # Is the header compilable?
-echo "$as_me:$LINENO: checking rpc/rpc.h usability" >&5
-echo $ECHO_N "checking rpc/rpc.h usability... $ECHO_C" >&6
+echo "$as_me:$LINENO: checking rpc/xdr.h usability" >&5
+echo $ECHO_N "checking rpc/xdr.h usability... $ECHO_C" >&6
 cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
@@ -3506,7 +3506,7 @@ cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
 $ac_includes_default
-#include <rpc/rpc.h>
+#include <rpc/xdr.h>
 _ACEOF
 rm -f conftest.$ac_objext
 if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
@@ -3542,15 +3542,15 @@ echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
 echo "${ECHO_T}$ac_header_compiler" >&6
 
 # Is the header present?
-echo "$as_me:$LINENO: checking rpc/rpc.h presence" >&5
-echo $ECHO_N "checking rpc/rpc.h presence... $ECHO_C" >&6
+echo "$as_me:$LINENO: checking rpc/xdr.h presence" >&5
+echo $ECHO_N "checking rpc/xdr.h presence... $ECHO_C" >&6
 cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
 cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
-#include <rpc/rpc.h>
+#include <rpc/xdr.h>
 _ACEOF
 if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
   (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
@@ -3584,25 +3584,25 @@ echo "${ECHO_T}$ac_header_preproc" >&6
 # So?  What about this header?
 case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
   yes:no: )
-    { echo "$as_me:$LINENO: WARNING: rpc/rpc.h: accepted by the compiler, rejected by the preprocessor!" >&5
-echo "$as_me: WARNING: rpc/rpc.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
-    { echo "$as_me:$LINENO: WARNING: rpc/rpc.h: proceeding with the compiler's result" >&5
-echo "$as_me: WARNING: rpc/rpc.h: proceeding with the compiler's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: rpc/xdr.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: rpc/xdr.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: rpc/xdr.h: proceeding with the compiler's result" >&5
+echo "$as_me: WARNING: rpc/xdr.h: proceeding with the compiler's result" >&2;}
     ac_header_preproc=yes
     ;;
   no:yes:* )
-    { echo "$as_me:$LINENO: WARNING: rpc/rpc.h: present but cannot be compiled" >&5
-echo "$as_me: WARNING: rpc/rpc.h: present but cannot be compiled" >&2;}
-    { echo "$as_me:$LINENO: WARNING: rpc/rpc.h:     check for missing prerequisite headers?" >&5
-echo "$as_me: WARNING: rpc/rpc.h:     check for missing prerequisite headers?" >&2;}
-    { echo "$as_me:$LINENO: WARNING: rpc/rpc.h: see the Autoconf documentation" >&5
-echo "$as_me: WARNING: rpc/rpc.h: see the Autoconf documentation" >&2;}
-    { echo "$as_me:$LINENO: WARNING: rpc/rpc.h:     section \"Present But Cannot Be Compiled\"" >&5
-echo "$as_me: WARNING: rpc/rpc.h:     section \"Present But Cannot Be Compiled\"" >&2;}
-    { echo "$as_me:$LINENO: WARNING: rpc/rpc.h: proceeding with the preprocessor's result" >&5
-echo "$as_me: WARNING: rpc/rpc.h: proceeding with the preprocessor's result" >&2;}
-    { echo "$as_me:$LINENO: WARNING: rpc/rpc.h: in the future, the compiler will take precedence" >&5
-echo "$as_me: WARNING: rpc/rpc.h: in the future, the compiler will take precedence" >&2;}
+    { echo "$as_me:$LINENO: WARNING: rpc/xdr.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: rpc/xdr.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: rpc/xdr.h:     check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: rpc/xdr.h:     check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: rpc/xdr.h: see the Autoconf documentation" >&5
+echo "$as_me: WARNING: rpc/xdr.h: see the Autoconf documentation" >&2;}
+    { echo "$as_me:$LINENO: WARNING: rpc/xdr.h:     section \"Present But Cannot Be Compiled\"" >&5
+echo "$as_me: WARNING: rpc/xdr.h:     section \"Present But Cannot Be Compiled\"" >&2;}
+    { echo "$as_me:$LINENO: WARNING: rpc/xdr.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: rpc/xdr.h: proceeding with the preprocessor's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: rpc/xdr.h: in the future, the compiler will take precedence" >&5
+echo "$as_me: WARNING: rpc/xdr.h: in the future, the compiler will take precedence" >&2;}
     (
       cat <<\_ASBOX
 ## -------------------------------------------- ##
@@ -3613,22 +3613,22 @@ _ASBOX
       sed "s/^/$as_me: WARNING:     /" >&2
     ;;
 esac
-echo "$as_me:$LINENO: checking for rpc/rpc.h" >&5
-echo $ECHO_N "checking for rpc/rpc.h... $ECHO_C" >&6
-if test "${ac_cv_header_rpc_rpc_h+set}" = set; then
+echo "$as_me:$LINENO: checking for rpc/xdr.h" >&5
+echo $ECHO_N "checking for rpc/xdr.h... $ECHO_C" >&6
+if test "${ac_cv_header_rpc_xdr_h+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
-  ac_cv_header_rpc_rpc_h=$ac_header_preproc
+  ac_cv_header_rpc_xdr_h=$ac_header_preproc
 fi
-echo "$as_me:$LINENO: result: $ac_cv_header_rpc_rpc_h" >&5
-echo "${ECHO_T}$ac_cv_header_rpc_rpc_h" >&6
+echo "$as_me:$LINENO: result: $ac_cv_header_rpc_xdr_h" >&5
+echo "${ECHO_T}$ac_cv_header_rpc_xdr_h" >&6
 
 fi
-if test $ac_cv_header_rpc_rpc_h = yes; then
+if test $ac_cv_header_rpc_xdr_h = yes; then
   :
 else
-  { { echo "$as_me:$LINENO: error: rpc/rpc.h include file missing" >&5
-echo "$as_me: error: rpc/rpc.h include file missing" >&2;}
+  { { echo "$as_me:$LINENO: error: rpc/xdr.h include file missing" >&5
+echo "$as_me: error: rpc/xdr.h include file missing" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
